version: "1.0"

services:
  afterglow-app:
    container_name: afterglow
    image: afterglow
    ports:
      - "8080:8080"
    networks:
      - afterglow-network

  afterglow-db:
    container_name: afterglow-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: afterglow
    ports:
      - "5432:5432"
    networks:
      - afterglow-network
volumes:
  afterglow-db:

networks:
  afterglow-network:
    driver: bridge
