version: "1.0"

services:
  afterglow-mysql:
    container_name: afterglow-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: S9o6u4T0
      MYSQL_DATABASE: afterglow
    ports:
      - "3307:3306"
    volumes:
      - G:/afterglow-db:/docker-entrypoint-initdb.d
    networks:
      - afterglow-network
  afterglow-app:
    container_name: afterglow
    image: afterglow
    ports:
      - "8080:8080"
    networks:
      - afterglow-network
volumes:
  afterglow-mysql:

networks:
  afterglow-network:
    driver: bridge