version: "1.0"

services:
  afterglow-app:
    container_name: afterglow
    image: afterglow
    ports:
      - "8080:8080"
    networks:
      - afterglow-network

  afterglow-db:
    container_name: afterglow-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: afterglow
    ports:
      - "3307:3306"
    networks:
      - afterglow-network
volumes:
  afterglow-db:

networks:
  afterglow-network:
    driver: bridge
